theblackjabgroup/Runnner

assets/custom-faq.css, assets/custom-faq.js, sections/faq.liquid
=> faq-section

sections/image-and-text.liquid
Added the image and text section
=> Added image-and-text section

sections/header.liquid
color schema & logo setting updated as per theme settings
=> color schema fixes & logo settings

sections/header.liquid
update the default icon & the mobile view margins & font-sizes
=> header alignment & icon fixes

sections/announcement-bar.liquid, sections/header.liquid, sections/main-list-collections.liquid, snippets/facets.liquid
header commented out as discussed with @syash7202 (patch work)
=> fixed mobile view issues

sections/header.liquid
The shop all <sub-menu item> now has animation of underline with proper spacing.
=> sub-menu child link underline styling fixed

sections/header.liquid
- Added 1vw margin for the header 
- fixed the submenu item (shop all) wrapping underline issue
=> header margin & underline fixes

development-deletion.sh, sections/header.liquid
added logic for [] handling on theme list output, & no development stores output.
=> terminal styling handled

sections/header.liquid
The CSS positioning issue within the header is resolved & made comparable to Bandit. Though it still covers the section above it while animating but this slight difference gives us ability for have optional stickness in header.
=> Header CSS position issue fixes

assets/featured-collection.js, sections/featured-collection.liquid, sections/image-with-text.liquid, templates/index.json
Converted section height from vh to px to get the right preview in the preview option in image with text & fixed a bug where the animation on letter of heading was not visible in featured collection
=> converted section height from vh to px & fixed animation

sections/content-block.liquid, sections/image-with-text.liquid
1. fixed video aspect ratio bug where the video was coming distorted and was not coming in actual size
2. fixed side padding issue
3. fixed arrow svg in button from 12.5 x 12.5 to 16 x 17
1. added theme settings variable for section padding
=> fixed video aspect ratio bug, padding issue & button arrow size

config/settings_schema.json, sections/footer.liquid, sections/sub-footer.liquid
removed brand info from theme setting 
fixed bugs of subfooter , padding and colr scheme issue and site credit also 
fixed margin issue in footer
=> removed brand info from theme setting and bug fixes of subfooter 

sections/header.liquid
This PR refactors the header’s mega-menu dropdown, which had the CSS stacking issue, to:
1. **Decouple** it from the bottom-bar indicator logic  
2. **Match** the required slide animation  
3. **Eliminate** the posiitioning issues  
4. **Allow easy tuning** of animation speed and hide-delay
=> Header animation fixes 

sections/main-product.liquid
PR contains minor testing changes for multiple components.
=> minor fixes for styling

snippets/cart-drawer.liquid
padding issue in product card, checkout button animation
=> cart drawer bugs

sections/sub-footer.liquid
=> fixed bugs of subfooter 

sections/header.liquid
Implemented the drawer style animation, removed unwanted styling & added specified routes.
=> Header styling & animation fix

sections/featured-collection.liquid, sections/image-with-text.liquid
added mute button when a video is selected as a background in image with text
1. fixed shop all button padding
2. Price and title font size
3. Space between Product title and product price
4. Made sold out button bold
5. Increased gap between product cards
6. Increased padding between product card and slider
7. fixed top margin between break line and product card
=> added mute button - image with text and fixed bugs in featured collection

sections/footer-group.json, sections/footer.liquid
increase logo size 
font -size and weight 
padding and margin issue fixed 
Icons row and column gap fixed
Code performance enhanced
Fixed the default store name when resetting the theme
=> footer bugs 

sections/main-cart-items.liquid, snippets/cart-drawer.liquid
checkout button sizing, vertical scroll bar compression, checkout button svg
=> fixed cart drawer and cart page bugs

sections/footer.liquid, sections/sub-footer.liquid
fixed font size in subfooter 
footer email and signup font size and height
=> Fixed font issue 

sections/Product-detail.liquid, sections/scrolling-marquee.liquid, templates/list-collections.json
made new section product detail
fixed scrolling marquee top and bottom border 
added in collection list page 
fixed json of collection list page
=> fixed scrolling -maqruee  and added new section product detail

sections/header.liquid
Patch for minor fixes, will be updated once the fix for the overlap issue is available.
=> header placement fixes

sections/announcement-bar.liquid, sections/header.liquid
The issue of the header overlapping the announcement bar is fixed.
=> header overlap issue fix

sections/outfit_inspiration.liquid
=> updated outfit inspiration

sections/header.liquid
The header  & mega menu img sizes are increased.
=> header height & mega menu img size increased

sections/content-block.liquid
added top margin - content block
=> content block bug fixed

config/settings_data.json, config/settings_schema.json, sections/header.liquid
Changes are concerning -> https://www.figma.com/design/haiquT7tNU4WjJEAeHhqJM/Theme---Bandit-running-?node-id=0-1&p=f
=> header styling & color code fixes 

sections/featured-collection.liquid, sections/image-with-text.liquid
This reverts commit 71701e635394d86242d325594da11bcf3d849d65.
=> Revert "fixed a part of accessibility issue"

sections/main-product.liquid
lazy loaded the images for product page
=> ci issue resolved

sections/content-block.liquid, sections/featured-collection.liquid, sections/image-with-text.liquid, templates/gift_card.liquid
1. Removed QR from gift card
2. fixed button animation in both buttons in gift card
3. Fixed mobile view of shopall button in featured collection
4. Fixed svg in featured collection and image with text
5. Changed play icon svg in content block to plus/minus
=> removed qr and fixed button animation in gift card and fixed mobile view of shop all button

sections/content-block.liquid
1. added text decoration for list and link
2. removed unnecessary right animation
3. solved padding issue
4. gave a left margin to icon
5. Fixed line height of accordion title
=> fixed bugs in content block

locales/en.default.schema.json, sections/featured-blog.liquid, sections/featured-collection.liquid, sections/product-difference.liquid, sections/signup-with-image.liquid, snippets/custom-button-slide-text.liquid, templates/index.json
1. Added primary button snippet file
1. removed customisation option for showing arrow only on hover
2. Changed notify me in stock to notify me when available
1. Renamed it to Signup With Image
2. Made width same of both buttons
1. Added play button in load more
1. Changed slider
=> added snippet file for primary button, solved text with image bugs & renamed it & fixed more css bugs

sections/featured-blog.liquid, sections/featured-collection.liquid, sections/image-with-text.liquid, snippets/primary-button.liquid
1. Renamed primary button snippet file
2. Fixed its working and css
3. Added mobile media query in primary button snippet
4. Rendered the button in -
a. Image with text
b. Featured Collection
c. Featured Blog
5. Added dual config for anchor tag and button tag in primary button
=> fixed primary button snippet and added it in files

sections/header.liquid
=> Shaurya header changes

assets/new-product-card.js, sections/featured-collection.liquid, sections/footer.liquid, sections/image-with-text.liquid, sections/main-404.liquid, sections/main-search.liquid, snippets/new-product-card.liquid, snippets/primary-button.liquid
1. Fixed z index issue in footer secondary button
2. Fixed reset cross position in search page
3. changed product card image nav arrow to chevron
4. fixed show arrow customisation bug in image with text
5. removed notify me when available pop up
6. made 404 page button as primary button
=> fixed bugs of image with text, search, footer, product card, 404 page

sections/main-product.liquid
fixed- size chart, mobile view, thumbnail strip
=> bug fixes for product page
